version: '3.9'

services:
  web:
    build:
      context: .
    restart: always
    command: > 
      sh -c "python manage.py makemigrations account employee project task commons && 
             python manage.py migrate --noinput && 
             python manage.py collectstatic --no-input && 
             uwsgi --socket :9000 --workers 4 --master --enable-threads --module config.wsgi"
    volumes:
      - static-volume:/app/staticfiles
      - media-volume:/app/mediafiles
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
  
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - web
    ports:
      - 80:8000
    volumes:
     - static-volume:/app/staticfiles
     - media-volume:/app/mediafiles

volumes:
  static-volume:
  media-volume:
  postgres-data:


