FROM python:3.11.4-slim-buster as builder
WORKDIR /usr/src/app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
# install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc
RUN pip install --upgrade pip
COPY . /usr/src/app/
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y --no-install-recommends netcat