# version: '3.8'

# services:
#   db:
#       image: postgres:12.16
#       restart: always
#       volumes:
#         - postgres_data:/var/lib/postgresql/data/
#       env_file:
#         - ./.env.prod.db
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: prod
#     restart: always
#     command: > 
#       sh -c "python manage.py makemigrations account employee project task commons && python manage.py migrate --noinput && python manage.py collectstatic --no-input && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
#     volumes:
#       - static_volume:/usr/src/app/staticfiles
#     port:
#       - 8000
#     env_file:
#       - ./.env.prod
#     depends_on:
#       - db
#   nginx:
#     build: ./nginx
#     restart: always
#     volumes:
#       - static_volume:/usr/src/app/staticfiles
#     expose:
#       - 1337:80
#     depends_on:
#       - web

# volumes:
#   postgres_data:
#   static_volume:
