version: '3.9'

services:
  web:
      build:
        context: .
      command: > 
        sh -c "python manage.py makemigrations &&
               python manage.py migrate --noinput && 
               python manage.py runserver 0.0.0.0:8000
              "
      volumes:
        - .:/app
        - static_volume:/app/vol/web/static
        - media_volume:/app/vol/web/media
      ports:
        - "8000:8000"
      env_file:
        - ./.env
      depends_on:
        - db
  db:
    image: "postgres:12.16"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  
  
volumes:
  postgres_data:
  static_volume:
  media_volume: