# Generated by Django 5.0.1 on 2024-02-01 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("62e5cc7d-9321-4461-babd-d166ef70e778"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="task id",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="task name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=225,
                        verbose_name="description",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "deadline",
                    models.DateField(blank=True, verbose_name="task deadline"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("NOT STARTED", "Not started"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=12,
                        verbose_name="task status",
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
                "db_table": "task",
            },
        ),
    ]
