# Generated by Django 5.0.1 on 2024-02-01 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2b589e6e-88f4-4e86-843e-0a55e07e038d"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="task id",
            ),
        ),
        migrations.AlterModelTable(
            name="task",
            table="tasks",
        ),
    ]
