# Generated by Django 4.2.11 on 2024-04-06 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c62e4008-e8c2-4dec-83ac-a56cd31db166"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="task id",
            ),
        ),
    ]
