# Generated by Django 4.2.11 on 2024-04-07 00:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("27091402-e6b5-454b-8659-d9063dee2f09"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="task id",
            ),
        ),
    ]
