# Generated by Django 4.2.11 on 2024-04-07 03:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0009_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("92137d2d-107e-4693-874d-521beb786e66"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="task id",
            ),
        ),
    ]
