# Generated by Django 5.0.1 on 2024-04-09 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0012_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e2d511f7-850d-4504-a437-eadf6161a756"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="task id",
            ),
        ),
    ]
