# Generated by Django 5.0.1 on 2024-02-07 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("d9453f64-9159-4140-84bc-5406567a3ed6"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="project id",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="project name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=225,
                        verbose_name="description",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "deadline",
                    models.DateField(blank=True, verbose_name="project deadline"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("NOT STARTED", "Not started"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=12,
                        verbose_name="project status",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="employee.department",
                    ),
                ),
                ("employees", models.ManyToManyField(to="employee.employee")),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "db_table": "projects",
            },
        ),
    ]
