# Generated by Django 5.0.1 on 2024-02-01 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("83e4af68-c71a-4276-8f52-afe6208da65e"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="project id",
            ),
        ),
        migrations.AlterModelTable(
            name="project",
            table="projects",
        ),
    ]
