# Generated by Django 5.0.1 on 2024-02-07 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a6338afb-627a-4132-b56c-6ad474006dc4"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="project id",
            ),
        ),
    ]
