# Generated by Django 4.2.10 on 2024-03-04 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2444aa0a-423e-4741-bb17-ed790a56c1c4"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="project id",
            ),
        ),
    ]
