# Generated by Django 5.0.1 on 2024-02-01 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_project_id_alter_project_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4c7db598-c820-45e2-92b1-b3e7ee6b9dc3"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="project id",
            ),
        ),
    ]
