# Generated by Django 4.2.11 on 2024-04-06 23:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5f10d122-508c-4f08-b99f-98c170ad2d05"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="project id",
            ),
        ),
    ]
