# Generated by Django 4.2.11 on 2024-04-07 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_alter_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f467ecda-2b46-45bd-a9ed-b7a63fb155ad"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="project id",
            ),
        ),
    ]
