# Generated by Django 4.2.10 on 2024-02-09 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("fc5ad7be-4486-4ef2-8250-956d5c420328"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="user id",
            ),
        ),
    ]
