# Generated by Django 4.2.11 on 2024-04-06 23:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("036e8fde-f06c-4e6c-aff5-053fc45487b1"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="user id",
            ),
        ),
    ]
