# Generated by Django 4.2.11 on 2024-04-06 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("369d1891-afff-4cc0-9b7a-6bb38dd9d790"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="user id",
            ),
        ),
    ]
