# Generated by Django 5.0.1 on 2024-04-09 23:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a5eba7dd-655c-49a3-96fc-4ada0d99661f"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="user id",
            ),
        ),
    ]
