# Generated by Django 5.0.1 on 2024-02-07 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("eedff558-3884-4657-b670-582b4c99f73e"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="employee id",
            ),
        ),
    ]
