# Generated by Django 5.0.1 on 2024-02-01 17:20

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1a32d62c-3019-42c0-a873-d8e3c8ff793a"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="employee id",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="phone number"
            ),
        ),
        migrations.AlterModelTable(
            name="address",
            table="addresses",
        ),
        migrations.AlterModelTable(
            name="department",
            table="departments",
        ),
        migrations.AlterModelTable(
            name="employee",
            table="employees",
        ),
        migrations.AlterModelTable(
            name="salary",
            table="salaries",
        ),
    ]
