# Generated by Django 5.0.1 on 2024-02-01 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_employee_id_alter_employee_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4076cc9d-f2ea-42e9-936a-3fd712341972"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="employee id",
            ),
        ),
    ]
