# Generated by Django 4.2.11 on 2024-04-07 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0007_alter_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3091e722-0d1b-4b5e-b2bc-9ac2a3b8e10a"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="employee id",
            ),
        ),
    ]
