# Generated by Django 4.2.11 on 2024-04-07 03:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_alter_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("686d8e97-aae3-46d8-9f57-502e31bb066f"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="employee id",
            ),
        ),
    ]
