# Generated by Django 4.2.11 on 2024-04-07 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_alter_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("93a5b07c-36f1-4516-a340-616a34302e4b"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="employee id",
            ),
        ),
    ]
