# Generated by Django 5.0.1 on 2024-04-09 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_alter_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(
                default="Victor", max_length=100, verbose_name="First name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(
                default="Ahumah", max_length=100, verbose_name="Last name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="other_names",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="other names"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5ee9dce7-1b30-4e72-9ec6-62475aee7985"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="employee id",
            ),
        ),
    ]
